version: '3.8'

services:
  mysql:
   image: mysql:8
   container_name: mysql-db
   environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
   ports:
      - "3306:3306"
   networks:
   - backend
   volumes:
    - mysql_data:/var/lib/mysql
   
  spring-api:
   build: .
   container_name: spring-api
   depends_on:
    - mysql
   networks:
   - backend
   ports:
      - "8080:8080" 
   environment:
    SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
    SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
    SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
    SPRING_DATASOURCE_PASSWORD:  ${SPRING_DATASOURCE_PASSWORD}
    SPRING_DATASOURCE_DRIVER_CLASS_NAME:  ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    SPRING_JPA_DATABASE_PLATFORM: ${SPRING_JPA_DATABASE_PLATFORM}
    SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
networks:
  backend:
volumes:
  mysql_data:
   